medical file api completed, patch and get
Esoty-Software-Solutions/dalilServer pull request #48
Opened 2023-04-19 12:37 UTC by aarushXL

created medical file routes for updating and getting

2023-04-19 12:55 UTC, afourteia requested changes

2023-04-19 12:55 UTC, afourteia commented on src/routers/subscriber.routes.js
> +.patch(customValidation(createSimpleMedicalFileValidator , "body") , createMedicalFilesController)
rename to updateSimpleMedicalFilevalidator for clarity

2023-04-19 12:55 UTC, afourteia commented on src/controllers/medicalFiles.controller.js
> +    const createMedicalFilesController = async (req, res) => {
update to updateMedicalFileController for clarity

2023-04-19 12:55 UTC, afourteia commented on src/services/medicalFilesServices.js
> +  }
No need for an extra service, just use the beneficiary services and then extract the data from it

2023-04-20 04:20 UTC, aarushXL commented on src/controllers/medicalFiles.controller.js
> +            const createResponse = await medicalFilesServices.createMedFileForSubscriber(query , {medicalFiles : req.body} , "create");
beneficiary services does not exists, should I create a new file for it ?

2023-04-20 08:41 UTC, afourteia approved these changes

2023-04-20 08:43 UTC, afourteia approved these changes

2023-04-20 08:43 UTC, merged